# Generated by Django 5.0.3 on 2024-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_desc', models.TextField(default='Default description')),
                ('recipe_image', models.ImageField(default='Default image', upload_to='recipenew')),
            ],
        ),
    ]
